"""
Problem database.
"""
from models import Problem, ProblemSet


ISL2022 = ProblemSet([
    Problem(
        problem_statement=r"Let $(a_n)_{n\geqslant1}$ be a sequence of positive real numbers with the property that $$(a_{n+1})^2+a_na_{n+2}\leqslant a_n+a_{n+2}$$ for all positive integers $n$. Show that $a_{2022}\leqslant1$.",
        source="ISL",
        year=2022,
        topic="A",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $k\geqslant2$ be an integer. Find the smallest integer $n\geqslant k+1$ with the property that there exists a set of $n$ distinct real numbers such that each of its elements can be written as a sum of $k$ other distinct elements of the set.",
        source="ISL",
        year=2022,
        topic="A",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Find all functions $f:\mathbb{R}^+\to\mathbb{R}^+$ such that, for every $x\in\mathbb{R}^+$, there exists a unique $y\in\mathbb{R}^+$ satisfying $$xf(y)+yf(x)\leqslant2.$$",
        source="ISL",
        year=2022,
        topic="A",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Let $n\geqslant3$ be an integer, and let $x_1$, $x_2$, \dots, $x_n$ be real numbers in the interval $[0,1]$. Let $s=x_1+\cdots+x_n$, and assume that $s\geqslant3$. Prove that there exist integers $i$ and $j$ with $1\leqslant i<j\leqslant n$ such that $$2^{j-i}x_ix_j>2^{s-3}.$$",
        source="ISL",
        year=2022,
        topic="A",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Find all positive integers $n\geqslant2$ for which there exist $n$ real numbers $a_1<\cdots<a_n$ and a real number $r>0$ such that the $\frac{1}{2}n(n-1)$ differences $a_j-a_i$ for $1\leqslant i<j\leqslant n$ are equal, in some order, to the numbers $r^1$, $r^2$, \dots, $r^{\frac{1}{2}n(n-1)}$.",
        source="ISL",
        year=2022,
        topic="A",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"We denote by $\mathcal{F}$ the set of all functions $f:\mathbb{R}\to\mathbb{R}$ such that $$f(x+f(y))=f(x)+f(y)$$ for every $x,y\in\mathbb{R}$. Find all rational numbers $q$ such that for every function $f\in\mathcal{F}$, there exists some $z\in\mathbb{R}$ satisfying $f(z)=qz$.",
        source="ISL",
        year=2022,
        topic="A",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"For a positive integer $n$ we denote by $s(n)$ the sum of the digits of $n$. Let $P(x)=x^n+a{n-1}x^{n-1}+\cdots+a_1x+a_0$ be a polynomial, where $n\geqslant2$ and $a_i$ is a positive integer for all $0\geqslant i\geqslant n-1$. Could it be the case that, for all positive integers $k$, $s(k)$ and $s(P(k))$ have the same parity?",
        source="ISL",
        year=2022,
        topic="A",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"For a positive integer $n$, an $n$-sequence is a sequence $(a_0,\dots,a_n)$ of non-negative integers satisfying the following condition: if $i$ and $j$ are non-negative integers with $i+j\leqslant n$, then $a_i+a_j\leqslant n$ and $a_{a_i+a_j}=a_{i+j}$. Let $f(n)$ be the number of $n$-sequences. Prove that there exist positive real numbers $c_1$, $c_2$ and $\lambda$ such that $$c_1\lambda^n<f(n)<c_2\lambda^n$$ for all positive integers $n$.",
        source="ISL",
        year=2022,
        topic="A",
        problem_number=8,
    ),
    Problem(
        problem_statement=r"A $\pm1$-sequence is a sequence of 2022 numbers $a_1$, \dots, $a_{2022}$, each equal to either $+1$ or $-1$. Determine the largest $C$ so that, for any $\pm1$-sequence, there exists an integer $k$ and indices $1\leqslant t_1<\cdots<t_k\leqslant2022$ so that $t_{i+1}-t_i\leqslant2$ for all $i$, and $$\left\lvert\sum_{i=1}^ka_{t_i}\right\rvert\geqslant C.$$",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"The Bank of Olso issues coins ade out of two types of metal: aluminium (denoted $A$) and copper (denoted $C$). Morgane has $n$ aluminium coins, and $n$ copper coins, and arranges her $2n$ coins in a row in some arbitrary initial order. Given a fixed positive integer $k\leqslant2n$, she repeatedly performs the following operation: identify the largest subsequence containing the $k$-th coin from the left which consists of consecutive coins made of the same metal, and move all coins in that subsequence to the left end of the row. For example, if $n=4$ and $k=4$, the process starting from the configuration $AACCCACA$ would be $$AACCCACA\to CCCAAACA\to AAACCCCA \to CCCCAAAA\to\cdots$$ Find all pairs $(n,k)$ with $1\leqslant k\leqslant2n$ such that for every initial configuration, at some point of the process there will be at most one aluminium coin adjecent to a copper coin.",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"In each square of a garden shaped like a $2022\times2022$ board, there is initially a tree of height 0. A gardener and a lumberjack alternate turns playing the following game, with the gardener taking the first turn: \begin{itemize}\item The gardener chooses a square in the garden. Each tree on that square and all the surrounding squares (of which there are at most 8) then becomes one unit taller. \item The lumberjack then chooses four different squares on the board. Each tree of positive height on those squares then becomes one unit shorter.\end{itemize} We say that a tree is \emph{majestic} if its height is at least $10^6$. Determine the largest number $K$ such that the gardener can ensure there are eventually $K$ majestic trees on the board, no matter how the lumberjack plays.",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Let $n>3$ be a positive integer. Suppose that $n$ children are arranged in a circle, and $n$ coins are distributed between them (some children may have no coins). At every step, a child with at least 2 coins may give 1 coin to each of their immediate neighbours on the right and left. Determine all initial distributions of coins from which it is possible that, after a finite number of steps, each child has exactly one coin.",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Let $m,n\geqslant2$ be integers, let $X$ be a set with $n$ elements, and let $X_1$, $X_2$, \dots, $X_m$ be pairwise distinct non-empty, not necessarily disjoint subsets of $X$. A function $f:X\to\{1,2,\dots,n+1\}$ is called \emph{nice} if there exists an index $k$ such that $$\sum_{x\in X_k}f(x)>\sum_{x\in X_i}f(x)$$ for all $i\neq k$. Prove that the number of nice functions is at least $n^n$.",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Let $n$ be a positive integer. We start with $n$ piles of pebbles, each initially containing a single pebble. One can perform moves of the following form: choose two piles, take an equal number of pebbles from each pile and form a new pile out of these pebbles. For each positive integer $n$, find the smallest number of non-empty piles that one can obtain by performing a finite sequence of moves of this form.",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Lucy starts by writing $s$ integer-valued 2022-tuples on a blackboard. After doing that, she can take any two (not necessarily distinct) tuples $\mathbf{v}=(v_1,\dots,v_{2022})$ and $\mathbf{w}=(w_1,\dots,w_{2022})$ that she has already written, and apply one of the following operations to obtain a new tuple: \begin{align*}\mathbf{v}+\mathbf{w} &= (v_1+w_1,\dots,v_{2022}+w_{2022}) \\ \mathbf{v}\circ\mathbf{w} &= (\max(v_1,w_1),\dots,\max(v_{2022},w_{2022}))\end{align*} and then write this tuple on the blackboard. \\ It turns out that, in this way, Lucy can write any integer-valued 2022-tuple on the blackboard after finitely many steps. What is the smallest possible number $s$ of tuples that she initially wrote?",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Alice fills the fields on an $n\times n$ board with numbers 1 to $n^2$, each number being used exactly once. She then counts the total number of good paths on the board. A \emph{good path} is a sequence of fields of arbitrary length (including 1) such that: \begin{enumerate}[(i)]\item The first field in the sequence is one that is only adjacent to fields with larger numbers, \item Each subsequent field in the sequence is adjacent to the previous field, \item The numbers written on the fields in the sequence are in increasing order.\end{enumerate} Two fields are considered adjacent if they share a common side. Find the smallest possible number of good paths Alice can obtain, as a function of $n$.",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=8,
    ),
    Problem(
        problem_statement=r"Let $f:\mathbb{N}_0\times\mathbb{N}_0\to\mathbb{N}_0$ be a bijection such that whenever $f(x_1,y_1)>f(x_2, y_2)$, we have $f(x_1+1,y_1)>f(x_2+1,y_2)$ and $f(x_1,y_1+1) > f(x_2, y_2+1)$. \\ Let $N$ be the number of pairs of integers $(x,y)$, with $0\leqslant x,y<100$, such that $f(x,y)$ is odd. Find the smallest and largest possible value of $N$.",
        source="ISL",
        year=2022,
        topic="C",
        problem_number=9
    ),
    Problem(
        problem_statement=r"A number is called \emph{Norwegian} if it has three distinct positive divisors whose sum is equal to 2022. Determine the smallest Norwegian number. (A Norwegian number may have more than 3 divisors.)",
        source="ISL",
        year=2022,
        topic="N",
        problem_number=1
    ),
    Problem(
        problem_statement=r"Find all positive integers $n>2$ such that $$n!\mid\prod_{\substack{p < q \leqslant n, \\ p,q \text{ primes}}}(p+q).$$",
        source="ISL",
        year=2022,
        topic="N",
        problem_number=2
    ),
    Problem(
        problem_statement=r"Let $a,d>1$ be a coprime, positive integers. Let $x_1=1$ and, for $k\geqslant1$, define $$x_{k+1}=\begin{cases}x_k+d & \text{if }a\text{ doesn't divide }x_k, \\ x_k/a & \text{if }a\text{ divides }x_k\end{cases}$$",
        source="ISL",
        year=2022,
        topic="N",
        problem_number=3
    ),
    Problem(
        problem_statement=r"Find all triples of positive integers $(a,b,p)$ with $p$ prime and $$a^p=b!+p.$$",
        source="ISL",
        year=2022,
        topic="N",
        problem_number=4
    ),
    Problem(
        problem_statement=r"For each $1\leqslant i\leqslant9$ and $T\in\mathbb{N}$, define $d_i(T)$ to be the total number of times the digit $i$ appears when all the multiples of 1829 between 1 and $T$ inclusive are written out in base 10. \\ Show that there are infinitely many $T\in\mathbb{N}$ such that there are precisely two distinct values among $d_1(T)$, $d_2(T)$, \dots, $d_9(T)$.",
        source="ISL",
        year=2022,
        topic="N",
        problem_number=5
    ),
    Problem(
        problem_statement=r"Let $Q$ be a set of prime numbers, not necessarily finite. For a positive integer $n$ consider its prime factorisation; define $p(n)$ to be the sum of all the exponents and $q(n)$ to be the sum of the exponents corresponding only to primes in $Q$. A positive integer $n$ is called \emph{special} if $p(n)+p(n+1)$ and $q(n)+q(n+1)$ are both even integers. Prove that there is a constant $c>0$ independent of the set $Q$ such that for any positive integer $N>100$, the number of special integers in $[1,N]$ is at least $cN$. \\ (For example, if $Q=\{3,7\}$, then $p(42)=3$, $q(42)=2$, $p(63)=3$, $q(63)=3$, $p(2022)=3$, $q(2022)=1$.)",
        source="ISL",
        year=2022,
        topic="N",
        problem_number=6
    ),
    Problem(
        problem_statement=r"Let $k$ be a positive integer and let $S$ be a finite set of odd prime numbers. Prove that there is at most one way (modulo rotation and reflection) to place the elements of $S$ around a circle such that the product of any two neighbors is of the form $x^2+x+k$ for some positive integer $x$.",
        source="ISL",
        year=2022,
        topic="N",
        problem_number=7
    ),
    Problem(
        problem_statement=r"Prove that $5^n-3^n$ is not divisible by $2^n+65$ for any positive integer $n$.",
        source="ISL",
        year=2022,
        topic="N",
        problem_number=8
    ),
])


ISL2021 = ProblemSet([
   Problem(
        problem_statement=r"Let $S$ be an infinite set of positive integers, such that there exist four pairwise distinct $a, b, c, d \in S$ with $\gcd(a,b)\neq\gcd(c,d)$. Prove that there exist three pairwise distinct $x, y, z \in S$ such that $\gcd(x,y)=\gcd(y,z)\neq\gcd(z,x)$.",
        source="ISL",
        year=2021,
        topic="C",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $n\geqslant 3$ be an integer. An integer $m \geqslant n + 1$ is called $n$-colourful if, given infinitely many marbles in each of $n$ colours $C_1$, $C_2$, \dots, $C_n$, it is possible to place $m$ of them around a circle so that in any group of $n + 1$ consecutive marbles there is at least one marble of colour $C_i$ for each $i=1,\dots, n$. Prove that there are only finitely many positive integers which are not $n$-colourful. Find the largest among them.",
        source="ISL",
        year=2021,
        topic="C",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"A thimblerigger has 2021 thimbles numbered from 1 through 2021. The thimbles are arranged in a circle in arbitrary order. The thimblerigger performs a sequence of 2021 moves; in the $k$th move, he swaps the positions of the two thimbles adjacent to thimble $k$. Prove that there exists a value of $k$ such that, in the $k$th move, the thimblerigger swaps some thimbles $a$ and $b$ such that $a < k < b$.",
        source="ISL",
        year=2021,
        topic="C",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"The kingdom of Anisotropy consists of $n$ cities. For every two cities there exists exactly one direct one-way road between them. We say that a path from $X$ to $Y$ is a sequence of roads such that one can move from $X$ to $Y$ along this sequence without returning to an already visited city. A collection of paths is called diverse if no road belongs to two or more paths in the collection. Let $A$ and $B$ be two distinct cities in Anisotropy. Let $N_{AB}$ denote the maximal number of paths in a diverse collection of paths from $A$ to $B$. Similarly, let $N_{BA}$ denote the maximal number of paths in a diverse collection of paths from $B$ to $A$. Prove that the equality $N_{AB}=N_{BA}$ holds if and only if the number of roads going out from $A$ is the same as the number of roads going out from $B$.",
        source="ISL",
        year=2021,
        topic="C",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Let $n$ and $k$ be two integers with $n > k \geqslant 1$. There are $2n + 1$ students standing in a circle. Each student $S$ has $2k$ neighbours — namely, the $k$ students closest to $S$ on the right, and the $k$ students closest to $S$ on the left. Suppose that $n + 1$ of the students are girls, and the other $n$ are boys. Prove that there is a girl with at least $k$ girls among her neighbours.",
        source="ISL",
        year=2021,
        topic="C",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"A hunter and an invisible rabbit play a game on an infinite square grid. First the hunter fixes a colouring of the cells with finitely many colours. The rabbit then secretly chooses a cell to start in. Every minute, the rabbit reports the colour of its current cell to the hunter, and then secretly moves to an adjacent cell that it has not visited before (two cells are adjacent if they share a side). The hunter wins if after some finite time either \begin{itemize}\item the rabbit cannot move; or \item the hunter can determine the cell in which the rabbit started. \end{itemize}Decide whether there exists a winning strategy for the hunter.",
        source="ISL",
        year=2021,
        topic="C",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Consider a checkered $3m \times 3m$ square, where $m$ is an integer greater than 1. A frog sits on the lower left corner cell $S$ and wants to get to the upper right corner cell $F$. The frog can hop from any cell to either the next cell to the right or the next cell upwards. Some cells can be sticky, and the frog gets trapped once it hops on such a cell. A set $X$ of cells is called \emph{blocking} if the frog cannot reach $F$ from $S$ when all the cells of $X$ are sticky. A blocking set is \emph{minimal} if it does not contain a smaller blocking set. \begin{enumerate}[(a)] \item Prove that there exists a minimal blocking set containing at least $3m^2-3m$ cells. \item Prove that every minimal blocking set contains at most $3m^2$ cells.\end{enumerate}",
        source="ISL",
        year=2021,
        topic="C",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Determine the largest $N$ for which there exists a table $T$ of integers with $N$ rows and $100$ columns that has the following properties: \begin{enumerate}[(i)] \item Every row contains the numbers $1$, $2$, \dots , $100$ in some order. \item For any two distinct rows $r$ and $s$, there is a column $c$ such that $\lvert T(r,c)-T(s,c)\rvert\geqslant2$.\end{enumerate}Here $T(r, c)$ means the number at the intersection of the row $r$ and the column $c$.",
        source="ISL",
        year=2021,
        topic="C",
        problem_number=8,
    ),
    Problem(
        problem_statement=r"Determine all integers $n\geqslant1$ for which there exists a pair of positive integers $(a, b)$ such that no cube of a prime divides $a^2 + b + 3$ and $$\frac{ab+3b+8}{a^2 + b + 3}=n.$$",
        source="ISL",
        year=2021,
        topic="N",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $n \geqslant 100$ be an integer. The numbers $n$, $n + 1$, \dots , $2n$ are written on $n + 1$ cards, one number per card. The cards are shuffled and divided into two piles. Prove that one of the piles contains two cards such that the sum of their numbers is a perfect square.",
        source="ISL",
        year=2021,
        topic="N",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Find all positive integers $n$ with the following property: the $k$ positive divisors of $n$ have a permutation $(d_1, d_2, \dots , d_k)$ such that for every $i = 1, 2, \dots , k$, the number $d_1 + \cdots + d_i$ is a perfect square.",
        source="ISL",
        year=2021,
        topic="N",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Alice is given a rational number $r > 1$ and a line with two points $B\neq R$, where point $R$ contains a red bead and point $B$ contains a blue bead. Alice plays a solitaire game by performing a sequence of moves. In every move, she chooses a (not necessarily positive) integer $k$, and a bead to move. If that bead is placed at point $X$, and the other bead is placed at $Y$, then Alice moves the chosen bead to point $X'$ with $\overrightarrow{YX'}=r^k\overrightarrow{YX}$. Alice’s goal is to move the red bead to the point $B$. Find all rational numbers $r > 1$ such that Alice can reach her goal in at most 2021 moves.",
        source="ISL",
        year=2021,
        topic="N",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Prove that there are only finitely many quadruples $(a, b, c, n)$ of positive integers such that $$n! = a^{n-1} + b^{n-1} + c^{n-1}.$$",
        source="ISL",
        year=2021,
        topic="N",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Determine all integers $n \geqslant 2$ with the following property: every $n$ pairwise distinct integers whose sum is not divisible by $n$ can be arranged in some order $a_1$, $a_2$, \dots , $a_n$ so that $n$ divides $1a_1+2a_2 + \cdots+na_n$.",
        source="ISL",
        year=2021,
        topic="N",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Let $a_1$, $a_2$, $a_3$, \dots be an infinite sequence of positive integers such that $a_{n+2m}$ divides $a_n+a_{n+m}$ for all positive integers $n$ and $m$. Prove that this sequence is eventually periodic, i.e.\ there exist positive integers $N$ and $d$ such that $a_n=a_{n+d}$ for all $n> N$.",
        source="ISL",
        year=2021,
        topic="N",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"For a polynomial $P(x)$ with integer coefficients let $P^1(x)=P(x)$ and $P^{k+1}(x)=P(P^k(x))$ for $k\geqslant1$. Find all positive integers $n$ for which there exists a polynomial $P(x)$ with integer coefficients such that for every integer $m\geqslant1$, the numbers $P^m(1)$, \dots , $P^m(n)$ leave exactly $\lceil n/2^m\rceil$ distinct remainders when divided by $n$.",
        source="ISL",
        year=2021,
        topic="N",
        problem_number=8,
    ),
    Problem(
        problem_statement=r"Let $n$ be an integer, and let $A$ be a subset of $\{0, 1, 2, 3, \dots , 5^n\}$ consisting of $4n + 2$ numbers. Prove that there exist $a, b, c \in A$ such that $a<b<c$ and $c + 2a > 3b$.",
        source="ISL",
        year=2021,
        topic="A",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"For every integer $n \geqslant 1$ consider the $n\times n$ table with entry $\left\lfloor\frac{ij}{n+1}\right\rfloor$ at the intersection of row $i$ and column $j$, for every $i = 1, \dots. , n$ and $j = 1, \dots , n$. Determine all integers $n\geqslant1$ for which the sum of the $n^2$ entries in the table is equal to $\frac{1}{4}n^2(n-1)$.",
        source="ISL",
        year=2021,
        topic="A",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Given a positive integer $n$, find the smallest value of $$\left\lfloor\frac{a_1}{1}\right\rfloor+\left\lfloor\frac{a_2}{2}\right\rfloor+\cdots+\left\lfloor\frac{a_n}{n}\right\rfloor$$ over all permutations $(a_1, a_2, \dots , a_n)$ of $(1, 2, \dots , n)$.",
        source="ISL",
        year=2021,
        topic="A",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Show that for all real numbers $x_1$, \dots , $x_n$ the following inequality holds: $$\sum_{i=1}^n\sum_{j=1}^n\sqrt{\lvert x_i-x_j\rvert}\leqslant\sum_{i=1}^n\sum_{j=1}^n\sqrt{\lvert x_i+x_j\rvert}$$",
        source="ISL",
        year=2021,
        topic="A",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Let $n \geqslant 2$ be an integer, and let $a_1$, $a_2$, \dots , $a_n$ be positive real numbers such that $a_1+a_2+\cdots+a_n=1$. Prove that $$\sum_{k=1}^n\frac{a_k}{1-a_k}(a_1+a_2+\cdots+a_{k-1})^2<\frac{1}{3}.$$",
        source="ISL",
        year=2021,
        topic="A",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Let $A$ be a finite set of (not necessarily positive) integers, and let $m\geqslant2$ be an integer. Assume that there exist non-empty subsets $B_1$, $B_2$, $B_3$, \dots , $B_m$ of $A$ whose elements add up to the sums $m^1$, $m^2$, $m^3$, \dots , $m^m$, respectively. Prove that $A$ contains at least $m/2$ elements.",
        source="ISL",
        year=2021,
        topic="A",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Let $n\geqslant1$ be an integer, and let $x_0$, $x_1$, \dots , $x_{n+1}$ be $n+2$ non-negative real numbers that satisfy $x_ix_{i+1}-x_{i-1}^2\geqslant1$ for all $i=1, 2, \dots , n$. Show that $$x_0+x_1+\cdots+x_n+x_{n+1}>\left(\frac{2n}{3}\right)^{3/2}.$$",
        source="ISL",
        year=2021,
        topic="A",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Determine all functions $f : \mathbb{R} \to \mathbb{R}$ that satisfy $$(f(a)-f(b))(f(b)-f(c))(f(c)-f(a))=f(ab^{2}+bc^{2}+ca^{2})-f(a^{2}b+b^{2}c+c^{2}a)$$ for all real numbers $a$, $b$, $c$.",
        source="ISL",
        year=2021,
        topic="A",
        problem_number=8,
    ),
])


ISL2020 = ProblemSet([
    Problem(
        problem_statement=r"For every positive integer $N$, determine the smallest real number $b_N$ such that, for all real $x$, $$\sqrt[N]{\frac{x^{2N}+1}{2}}\leqslant b_N(x-1)^{2}+x.$$",
        source="ISL",
        year=2020,
        topic="A",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $\mathcal{A}$ denote the set of all polynomials in three variables $x$, $y$, $z$ with integer coefficients. Let $\mathcal{B}$ denote the subset of $\mathcal{A}$ formed by all polynomials which can be expressed as $$(x+y+z)P(x,y,z)+(xy+yz+zx)Q(x,y,z)+xyzR(x,y,z)$$ with $P, Q, R \in \mathcal{A}$. Find the smallest non-negative integer $n$ such that $x^iy^jz^k\in\mathcal{B}$ for all non-negative integers $i$, $j$, $k$ satisfying $i+j+k\geqslant n$.",
        source="ISL",
        year=2020,
        topic="A",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Suppose that $a$, $b$, $c$, $d$ are positive real numbers satisfying $(a+c)(b+d)=ac+bd$. Find the smallest possible value of $$\frac{a}{b}+\frac{b}{c}+\frac{c}{d}+\frac{d}{a}.$$",
        source="ISL",
        year=2020,
        topic="A",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Let $a$, $b$, $c$, $d$ be four real numbers such that $a\geqslant b\geqslant c\geqslant d>0$ and $a+b+c+d=1$. Prove that $$(a+2b+3c+4d)a^ab^bc^cd^d<1.$$",
        source="ISL",
        year=2020,
        topic="A",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"A magician intends to perform the following trick. She announces a positive integer $n$, along with $2n$ real numbers $x_1 < \cdots < x_{2n}$, to the audience. A member of the audience then secretly chooses a polynomial $P(x)$ of degree $n$ with real coefficients, computes the $2n$ values $P(x_1)$, \dots , $P(x_{2n})$, and writes down these $2n$ values on the blackboard in non-decreasing order. After that the magician announces the secret polynomial to the audience. Can the magician find a strategy to perform such a trick?",
        source="ISL",
        year=2020,
        topic="A",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Determine all functions $f:\mathbb{Z}\to\mathbb{Z}$ such that $$f^{a^2+b^2}(a+b)=af(a)+bf(b)$$ for every $a,b\in\mathbb{Z}$.",
        source="ISL",
        year=2020,
        topic="A",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Let $n$ and $k$ be positive integers. Prove that for $a_1,\dots,a_n\in [1, 2^k]$ one has $$\sum_{i=1}^n\frac{a_i}{\sqrt{a_1^2+\cdots+a_i^2}}\leqslant4\sqrt{kn}.$$",
        source="ISL",
        year=2020,
        topic="A",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Determine all functions $f:\mathbb{R}^+\to\mathbb{R}^+$ such that, for all positive real numbers $x$ and $y$, $$f(x+f(xy))+y=f(x)f(y)+1.$$",
        source="ISL",
        year=2020,
        topic="A",
        problem_number=8,
    ),
    Problem(
        problem_statement=r"Let $n$ be a positive integer. Find the number of permutations $a_1$, $a_2$, \dots , $a_n$ of the sequence 1, 2, \dots , $n$ satisfying $$a_1\leqslant2a_2\leqslant3a_3\leqslant\cdots\leqslant na_n.$$",
        source="ISL",
        year=2020,
        topic="C",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"In a regular 100-gon, 41 vertices are colored black and the remaining 59 vertices are colored white. Prove that there exist 24 convex quadrilaterals $Q_1$, \dots , $Q_{24}$ whose corners are vertices of the 100-gon, so that \begin{itemize}\item the quadrilaterals $Q_1$, \dots , $Q_{24}$ are pairwise disjoint, and \item every quadrilateral $Q_i$ has three corners of one color and one corner of the other color.\end{itemize}",
        source="ISL",
        year=2020,
        topic="C",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Let $n\geqslant2$ be an integer. On a slope of a mountain, $n^2$ checkpoints are marked, numbered from 1 to $n^2$ from the bottom to the top. Each of two cable car companies, $A$ and $B$, operates $k$ cable cars numbered from 1 to $k$; each cable car provides a transfer from some checkpoint to a higher one. For each company, and for any $i$ and $j$ with $1\leqslant i<j\leqslant k$, the starting point of car $j$ is higher than the starting point of car $i$; similarly, the finishing point of car $j$ is higher than the finishing point of car $i$. Say that two checkpoints are linked by some company if one can start from the lower checkpoint and reach the higher one by using one or more cars of that company (no movement on foot is allowed). Determine the smallest $k$ for which one can guarantee that there are two checkpoints that are linked by each of the two companies.",
        source="ISL",
        year=2020,
        topic="C",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"The Fibonacci numbers $F_0$, $F_1$, $F_2$, \dots are defined inductively by $F_0=0$, $F_1=1$, and $F_{n+1}=F_n+F_{n-1}$ for $n\geqslant1$. Given an integer $n\geqslant2$, determine the smallest size of a set $S$ of integers such that for every $k=2, 3, \dots , n$ there exist some $x, y\in S$ such that $x-y=F_k$.",
        source="ISL",
        year=2020,
        topic="C",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Let $p$ be an odd prime, and put $N=\frac{1}{4}(p^3-p)-1$. The numbers 1, 2, \dots , $N$ are painted arbitrarily in two colors, red and blue. For any positive integer $n\leqslant N$, denote by $r(n)$ the fraction of integers in $\{1, 2, \dots , n\}$ that are red. Prove that there exists a positive integer $a\in \{1, 2, \dots , p-1\}$ such that $r(n)\neq a/p$ for all $n=1, 2, \dots , N$.",
        source="ISL",
        year=2020,
        topic="C",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"$4n$ coins of weights 1, 2, 3, \dots , $4n$ are given. Each coin is colored in one of $n$ colors and there are four coins of each color. Show that all these coins can be partitioned into two sets with the same total weight, such that each set contains two coins of each color.",
        source="ISL",
        year=2020,
        topic="C",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Consider any rectangular table having finitely many rows and columns, with a real number $a(r,c)$ in the cell in row $r$ and column $c$. A pair $(R,C)$, where $R$ is a set of rows and $C$ a set of columns, is called a \emph{saddle pair} if the following two conditions are satisfied: \begin{enumerate}[(i)]\item For each row $r'$, there is $r\in R$ such that $a(r,c)\geqslant a(r',c)$ for all $c\in C$; \item For each column $c'$, there is $c\in C$ such that $a(r,c)\leqslant a(r, c')$ for all $r \in R$.\end{enumerate} A saddle pair $(R, C)$ is called a \emph{minimal pair} if for each saddle pair $(R', C')$ with $R'\subseteq R$ and $C'\subseteq C$, we have $R'=R$ and $C'=C$. Prove that any two minimal pairs contain the same number of rows.",
        source="ISL",
        year=2020,
        topic="C",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Players $A$ and $B$ play a game on a blackboard that initially contains 2020 copies of the number 1. In every round, player $A$ erases two numbers $x$ and $y$ from the blackboard, and then player $B$ writes one of the numbers $x+y$ and $\lvert x-y\rvert$ on the blackboard. The game terminates as soon as, at the end of some round, one of the following holds: \begin{enumerate}[(a)] \item one of the numbers on the blackboard is larger than the sum of all other numbers; \item there are only zeros on the blackboard. \end{enumerate} Player $B$ must then give as many cookies to player $A$ as there are numbers on the blackboard. Player $A$ wants to get as many cookies as possible, whereas player $B$ wants to give as few as possible. Determine the number of cookies that $A$ receives if both players play optimally.",
        source="ISL",
        year=2020,
        topic="C",
        problem_number=8,
    ),

    Problem(
        problem_statement=r"Given a positive integer $k$, show that there exists a prime $p$ such that one can choose distinct integers $a_1$, $a_2$, \dots , $a_{k+3}\in\{1, 2, \dots , p-1\}$ such that $p$ divides $a_ia_{i+1}a_{i+2}a_{i+3}-i$ for all $i=1, 2, \dots , k$.",
        source="ISL",
        year=2020,
        topic="N",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"For each prime $p$, there is a kingdom of $p$-Landia consisting of $p$ islands numbered 1, 2, \dots , $p$. Two distinct islands numbered $n$ and $m$ are connected by a bridge if and only if $p$ divides $(n^2 - m + 1)(m^2 - n + 1)$. The bridges may pass over each other, but cannot cross. Prove that for infinitely many $p$ there are two islands in $p$-Landia not connected by a chain of bridges.",
        source="ISL",
        year=2020,
        topic="N",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Let $n\geqslant2$ be an integer. Does there exist a sequence $(a_1, \dots , a_n)$ of positive integers with not all terms being equal such that the arithmetic mean of every two terms is equal to the geometric mean of some (one or more) terms in this sequence?",
        source="ISL",
        year=2020,
        topic="N",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"For any odd prime $p$ and any integer $n$, let $d_p(n)\in \{0, 1, \dots , p-1\}$ denote the remainder when $n$ is divided by $p$. We say that $(a_0, a_1, a_2, \dots)$ is a $p$-sequence, if $a_0$ is a positive integer coprime to $p$, and $a_{n+1}=a_n+d_p(a_n)$ for $n\geqslant0$. \begin{enumerate}[(a)] \item Do there exist infinitely many primes $p$ for which there exist $p$-sequences $(a_0, a_1, a_2, \dots)$ and $(b_0, b_1, b_2, \dots)$ such that $a_n > b_n$ for infinitely many $n$, and $b_n>a_n$ for infinitely many $n$? \item Do there exist infinitely many primes $p$ for which there exist $p$-sequences $(a_0, a_1, a_2, \dots)$ and $(b_0, b_1, b_2, \dots)$ such that $a_0 < b_0$, but an $a_n>b_n$ for all $n\geqslant1$?\end{enumerate}",
        source="ISL",
        year=2020,
        topic="N",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Determine all functions $f$ defined on the set of all positive integers and taking non-negative integer values, satisfying the three conditions: \begin{enumerate}[(i)] \item $f(n)\neq0$ for at least one $n$; \item $f(xy)=f(x)+f(y)$ for every positive integers $x$ and $y$; \item there are infinitely many positive integers $n$ such that $f(k)=f(n-k)$ for all $k<n$.\end{enumerate}",
        source="ISL",
        year=2020,
        topic="N",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"For a positive integer $n$, let $d(n)$ be the number of positive divisors of $n$, and let $\phi(n)$ be the number of positive integers not exceeding $n$ which are coprime to $n$. Does there exist a constant $C$ such that $$\frac{\phi(d(n))}{d(\phi(n))}\leqslant C$$ for all $n\geqslant1$?",
        source="ISL",
        year=2020,
        topic="N",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Let $\mathcal{S}$ be a set consisting of $n\geqslant3$ positive integers, none of which is a sum of two other distinct members of $\mathcal{S}$. Prove that the elements of $\mathcal{S}$ may be ordered as $a_1$, $a_2$, \dots , $a_n$ so that $a_i$ does not divide $a_{i-1}+a_{i+1}$ for all $i=2, 3, . . . , n-1$.",
        source="ISL",
        year=2020,
        topic="N",
        problem_number=7,
    ),
])


ISL2019 = ProblemSet([
    Problem(
        problem_statement=r"Determine all functions $f:\mathbb{Z}\to\mathbb{Z}$ such that, for all integers $a$ and $b$, $$f(2a)+2f(b)=f(f(a+b)).$$",
        source="ISL",
        year=2019,
        topic="A",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $u_1$, $u_2$, \dots , $u_{2019}$ be real numbers satisfying $$u_1+u_2+\cdots+u_{2019}=0$$ and $$u_1^2+u_2^2+\cdots+u_{2019}^2.$$ Let $a=\min(u_1, u_2, \dots , u_{2019})$ and $b=\max(u_1, u_2, \dots , u_{2019})$. Prove that $$ab\leqslant-\frac{1}{2019}.$$",
        source="ISL",
        year=2019,
        topic="A",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Let $n\geqslant3$ be a positive integer and let $(a_1, a_2, \dots , a_n)$ be a strictly increasing sequence of $n$ positive real numbers with sum equal to 2. Let $X$ be a subset of $\{1, 2, \dots , n\}$ such that the value of $$\left\lvert 1-\sum_{i\in X}a_i\right\rvert$$ is minimised. Prove that there exists a strictly increasing sequence of $n$ positive real numbers $(b_1, b_2, \dots , b_n)$ with sum equal to 2 such that $$\sum_{i\in X}b_i=1.$$",
        source="ISL",
        year=2019,
        topic="A",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Let $n\geqslant2$ be a positive integer and $a_1$, $a_2$, \dots , $a_n$ be real numbers such that $$a_1+a_2+\cdots+a_n=0.$$ Define the set $A$ by $$A=\{(i,j)\mid 1\leqslant i<j\leqslant n,\lvert a_i-a_j\rvert\geqslant1\}.$$ Prove that, if $A$ is not empty, then $$\sum_{(i,j)\in A}a_ia_j<0.$$",
        source="ISL",
        year=2019,
        topic="A",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Let $x_1$, $x_2$, \dots , $x_n$ be different real numbers. Prove that $$\sum_{1\leqslant i\leqslant n}\prod_{j\neq i}\frac{1-x_ix_j}{x_i-x_j}=\begin{cases}0, & \text{ if }n\text{ is even;} \\ 1, & \text{ if }n\text{ is odd.}\end{cases}$$",
        source="ISL",
        year=2019,
        topic="A",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"A polynomial $P(x, y, z)$ in three variables with real coefficients satisfies the identities $$P(x,y,z)=P(x,y,xy-z)=P(x,zx-y,z)=P(yz-x,y,z).$$ Prove that there exists a polynomial $F(t)$ in one variable such that $$P(x,y,z)=F(x^2+y^2+z^2-xyz).$$",
        source="ISL",
        year=2019,
        topic="A",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"We consider functions $f : \mathbb{Z}\to\mathbb{Z}$ satisfying $$f(f(x+y)+y)=f(f(x)+y)$$ for all integers $x$ and $y$. For such a function, we say that an integer $v$ is $f$-rare if the set $$X_v=\{x\in \mathbb{Z} : f(x)=v\}.$$ is finite and nonempty. \begin{enumerate}[(a)] \item Prove that there exists such a function $f$ for which there is an $f$-rare integer. \item Prove that no such function $f$ can have more than one $f$-rare integer.\end{enumerate}",
        source="ISL",
        year=2019,
        topic="A",
        problem_number=7,
    ),


    Problem(
        problem_statement=r"The infinite sequence $a_0$, $a_1$, $a_2$, \dots  of (not necessarily different) integers has the following properties: $0\leqslant a_i \leqslant i$ for all integers $i\geqslant0$, and $$\binom{k}{a_0}+\binom{k}{a_1}+\cdots+\binom{k}{a_k}=2^k$$ for all integers $k \geqslant 0$. Prove that all integers $N\geqslant0$ occur in the sequence (that is, for all $N \geqslant 0$, there exists $i\geqslant0$ with $a_i=N$).",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"You are given a set of $n$ blocks, each weighing at least 1; their total weight is $2n$. Prove that for every real number $r$ with $0\leqslant r\leqslant2n-2$ you can choose a subset of the blocks whose total weight is at least $r$ but at most $r+2$.",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Let $n$ be a positive integer. Harry has $n$ coins lined up on his desk, each showing heads or tails. He repeatedly does the following operation: if there are $k$ coins showing heads and $k>0$, then he flips the $k$th coin over; otherwise he stops the process. (For example, the process starting with $THT$ would be $THT \to HHT \to HTT \to TTT$, which takes three steps.) Letting $C$ denote the initial configuration (a sequence of $n$ $H$’s and $T$’s), write $\ell(C)$ for the number of steps needed before all coins show $T$. Show that this number $\ell(C)$ is finite, and determine its average value over all $2^n$ possible initial configurations $C$.",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"On a flat plane in Camelot, King Arthur builds a labyrinth $\mathcal{L}$ consisting of $n$ walls, each of which is an infinite straight line. No two walls are parallel, and no three walls have a common point. Merlin then paints one side of each wall entirely red and the other side entirely blue. At the intersection of two walls there are four corners: two diagonally opposite corners where a red side and a blue side meet, one corner where two red sides meet, and one corner where two blue sides meet. At each such intersection, there is a two-way door connecting the two diagonally opposite corners at which sides of different colours meet. After Merlin paints the walls, Morgana then places some knights in the labyrinth. The knights can walk through doors, but cannot walk through walls. Let $k(\mathcal{L})$ be the largest number $k$ such that, no matter how Merlin paints the labyrinth $\mathcal{L}$, Morgana can always place at least $k$ knights such that no two of them can ever meet. For each $n$, what are all possible values for $k(\mathcal{L})$, where $\mathcal{L}$ is a labyrinth with $n$ walls?",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"On a certain social network, there are 2019 users, some pairs of which are friends, where friendship is a symmetric relation. Initially, there are 1010 people with 1009 friends each and 1009 people with 1010 friends each. However, the friendships are rather unstable, so events of the following kind may happen repeatedly, one at a time: \\Let $A$, $B$, and $C$ be people such that $A$ is friends with both $B$ and $C$, but $B$ and $C$ are not friends; then $B$ and $C$ become friends, but $A$ is no longer friends with them. \\Prove that, regardless of the initial friendships, there exists a sequence of such events after which each user is friends with at most one other user.",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Let $n>1$ be an integer. Suppose we are given $2n$ points in a plane such that no three of them are collinear. The points are to be labelled $A_1$, $A_2$, \dots , $A_{2n}$ in some order. We then consider the $2n$ angles $\angle A_1A_2A_3$, $\angle A_2A_3A_4$, \dots , $\angle A_{2n-2}A_{2n-1}A_{2n}$, $\angle A_{2n-1}A_{2n}A_1$, $\angle A_{2n}A_1A_{2}$. We measure each angle in the way that gives the smallest positive value (i.e.\ between $0^{\circ}$ and $180^{\circ}$). Prove that there exists an ordering of the given points such that the resulting $2n$ angles can be separated into two groups with the sum of one group of angles equal to the sum of the other group.",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"There are 60 empty boxes $B_1$, \dots , $B_{60}$ in a row on a table and an unlimited supply of pebbles. Given a positive integer $n$, Alice and Bob play the following game. In the first round, Alice takes $n$ pebbles and distributes them into the $60$ boxes as she wishes. Each subsequent round consists of two steps: \begin{enumerate}[(a)] \item Bob chooses an integer $k$ with $1 \leqslant k \leqslant 59$ and splits the boxes into the two groups $B_1$, \dots , $B_k$ and $B_{k+1}$, \dots , $B_{60}$. \item Alice picks one of these two groups, adds one pebble to each box in that group, and removes one pebble from each box in the other group. \end{enumerate} Bob wins if, at the end of any round, some box contains no pebbles. Find the smallest $n$ such that Alice can prevent Bob from winning.",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Alice has a map of Wonderland, a country consisting of $n\geqslant2$ towns. For every pair of towns, there is a narrow road going from one town to the other. One day, all the roads are declared to be ``one way'' only. Alice has no information on the direction of the roads, but the King of Hearts has offered to help her. She is allowed to ask him a number of questions. For each question in turn, Alice chooses a pair of towns and the King of Hearts tells her the direction of the road connecting those two towns. Alice wants to know whether there is at least one town in Wonderland with at most one outgoing road. Prove that she can always find out by asking at most $4n$ questions.",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=8,
    ),
    Problem(
        problem_statement=r"For any two different real numbers $x$ and $y$, we define $D(x, y)$ to be the unique integer $d$ satisfying $2^d \leqslant \lvert x-y\rvert < 2^{d+1}$. Given a set of reals $\mathcal{F}$, and an element $x\in\mathcal{F}$ , we say that the \emph{scales} of $x$ in $\mathcal{F}$ are the values of $D(x, y)$ for $y\in\mathcal{F}$ with $x\neq y$. Let $k$ be a given positive integer. Suppose that each member $x$ of $\mathcal{F}$ has at most $k$ different scales in $F$ (note that these scales may depend on $x$). What is the maximum possible size of $\mathcal{F}$?",
        source="ISL",
        year=2019,
        topic="C",
        problem_number=9,
    ),


    Problem(
        problem_statement=r"Find all pairs $(m, n)$ of positive integers satisfying the equation $$(2^n-1)(2^n-2)(2^n-4)\cdots(2^n-2^{n-1})=m!$$",
        source="ISL",
        year=2019,
        topic="N",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Find all triples $(a, b, c)$ of positive integers such that $a^3 + b^3 + c^3 = (abc)^2$.",
        source="ISL",
        year=2019,
        topic="N",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"We say that a set $S$ of integers is \emph{rootiful} if, for any positive integer $n$ and any $a_0, a_1, \dots , a_n\in S$, all integer roots of the polynomial $a_0+a_1x+\cdots+a_nx^n$ are also in $S$. Find all rootiful sets of integers that contain all numbers of the form $2^a-2^b$ for positive integers $a$ and $b$.",
        source="ISL",
        year=2019,
        topic="N",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"A positive integer constant $C$ is given. Find all functions $f : \mathbb{N}\to\mathbb{N}$ such that, for all positive integers $a$ and $b$ satisfying $a+b>C$, $$a+f(b)\mid a^2+bf(a).$$",
        source="ISL",
        year=2019,
        topic="N",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Let $a$ be a positive integer. We say that a positive integer $b$ is $a$-good if $\binom{an}{b}-1$ is divisible by $an+1$ for all positive integers $n$ with $an\geqslant b$. Suppose $b$ is a positive integer such that $b$ is $a$-good, but $b+2$ is not $a$-good. Prove that $b+1$ is prime.",
        source="ISL",
        year=2019,
        topic="N",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Let $H=\{\left\lfloor i\sqrt{2}\right\rfloor : i \in \mathbb{N}\}= \{1, 2, 4, 5, 7, . . .\}$, and let $n$ be a positive integer. Prove that there exists a constant $C$ such that, if $A \subset \{1, 2, \dots , n\}$ satisfies $\lvert A\rvert\geqslant C\sqrt{n}$, then there exist $a, b\in A$ such that $a-b\in H$.",
        source="ISL",
        year=2019,
        topic="N",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Prove that there is a constant $c>0$ and infinitely many positive integers $n$ with the following property: there are infinitely many positive integers that cannot be expressed as the sum of fewer than $cn\log(n)$ pairwise coprime $n$th powers.",
        source="ISL",
        year=2019,
        topic="N",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Let $a$ and $b$ be two positive integers. Prove that the integer $$a^2+\left\lceil\frac{4a^2}{b}\right\rceil$$ is not a square.",
        source="ISL",
        year=2019,
        topic="N",
        problem_number=8,
    ),
])


ISL2018 = ProblemSet([
    Problem(
        problem_statement=r"Determine all functions $f : \mathbb{Q}^+\to\mathbb{Q}^+$ satisfying $$f(x^2f(y)^2)=f(x)^2f(y)$$ for all $x, y \in \mathbb{Q}^+$",
        source="ISL",
        year=2018,
        topic="A",
        problem_number=1,
    ),
        Problem(
        problem_statement=r"Find all positive integers $n \geqslant 3$ for which there exist real numbers $a_1$, $a_2$, \dots , $a_n$, $a_{n+1}=a_1$, $a_{n+2}=a_2$ such that $$a_ia_{i+1}+1=a_{i+2}$$ for all $i=1, 2, \dots , n$.",
        source="ISL",
        year=2018,
        topic="A",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Given any set $S$ of positive integers, show that at least one of the following two assertions holds: \begin{enumerate}[(1)]\item There exist distinct finite subsets $F$ and $G$ of $S$ such that $\sum_{x\in F}1/x=\sum_{x\in G} 1/x$; \item There exists a positive rational number $r<1$ such that $\sum_{x\in F}1/x\neq r$ for all finite subsets $F$ of $S$.\end{enumerate}",
        source="ISL",
        year=2018,
        topic="A",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Let $a_0$, $a_1$, $a_2$, $\dots$  be a sequence of real numbers such that $a_0=0$, $a_1=1$, and for every $n\geqslant2$ there exists $1\leqslant k\leqslant n$ satisfying $$a_n=\frac{a_{n-1}+\cdots+a_{n-k}}{k}.$$ Find the maximal possible value of $a_{2018}-a_{2017}$.",
        source="ISL",
        year=2018,
        topic="A",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Determine all functions $f : (0,\infty)\to\mathbb{R}$ satisfying $$\left(x+\frac{1}{x}\right)f(y)=f(xy)+f\left(\frac{y}{x}\right)$$ for all $x,y>0$.",
        source="ISL",
        year=2018,
        topic="A",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Let $m, n \geqslant 2$ be integers. Let $f(x_1, \dots , x_n)$ be a polynomial with real coefficients such that $$f(x_1, \dots , x_n)=\left\lfloor\frac{x_1 + \dots + x_n}{m}\right\rfloor\qquad\text{for every }x_1, \dots , x_n \in \{0, 1, \dots , m-1\}.$$ Prove that the total degree of $f$ is at least $n$.",
        source="ISL",
        year=2018,
        topic="A",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Find the maximal value of $$S=\sqrt[3]{\frac{a}{b+7}}+\sqrt[3]{\frac{b}{c+7}}+\sqrt[3]{\frac{c}{d+7}}+\sqrt[3]{\frac{d}{a+7}},$$ where $a$, $b$, $c$, $d$ are nonnegative real numbers which satisfy $a+b+c+d=100$.",
        source="ISL",
        year=2018,
        topic="A",
        problem_number=7,
    ),



    Problem(
        problem_statement=r"Let $n\geqslant3$ be an integer. Prove that there exists a set $S$ of $2n$ positive integers satisfying the following property: For every $m=2, 3, \dots , n$ the set $S$ an be partitioned into two subsets with equal sums of elements, with one of subsets of cardinality $m$.",
        source="ISL",
        year=2018,
        topic="C",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Queenie and Horst play a game on a $20\times20$ chessboard. In the beginning the board is empty. In every turn, Horst places a black knight on an empty square in such a way that his new knight does not attack any previous knights. Then Queenie places a white queen on an empty square. The game gets finished when somebody cannot move. Find the maximal positive $K$ such that, regardless of the strategy of Queenie, Horst can put at least $K$ knights on the board.",
        source="ISL",
        year=2018,
        topic="C",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Let $n$ be a given positive integer. Sisyphus performs a sequence of turns on a board consisting of $n+1$ squares in a row, numbered $0$ to $n$ from left to right. Initially, $n$ stones are put into square $0$, and the other squares are empty. At every turn, Sisyphus chooses any nonempty square, say with $k$ stones, takes one of those stones and moves it to the right by at most $k$ squares (the stone should stay within the board). Sisyphus' aim is to move all $n$ stones to square $n$. Prove that Sisyphus cannot reach the aim in less than $$\left\lceil\frac{n}{1}\right\rceil+\left\lceil\frac{n}{2}\right\rceil+\left\lceil\frac{n}{3}\right\rceil+\cdots+\left\lceil\frac{n}{n}\right\rceil$$ turns.",
        source="ISL",
        year=2018,
        topic="C",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"TODO!",
        source="ISL",
        year=2018,
        topic="C",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Let $k$ be a positive integer. The organising committee of a tennis tournament is to schedule the matches for $2k$ players so that every two players play once, each day exactly one match is played, and each player arrives to the tournament site the day of his first match, and departs the day of his last match. For every day a player is present on the tournament, the committee has to pay 1 coin to the hotel. The organisers want to design the schedule so as to minimise the total cost of all players' stays. Determine this minimum cost.",
        source="ISL",
        year=2018,
        topic="C",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Let $a$ and $b$ be distinct positive integers. The following infinite process takes place on an initially empty board. \begin{enumerate}[(i)]\item If there is at least a pair of equal numbers on the board, we choose such a pair and increase one of its components by $a$ and the other by $b$. \item If no such pair exists, we write down two times the number 0.\end{enumerate}Prove that, no matter how we make the choices in \emph{(i)}, operation \emph{(ii)} will be performed only finitely many times.",
        source="ISL",
        year=2018,
        topic="C",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Consider 2018 pairwise crossing circles no three of which are concurrent. These circles subdivide the plane into regions bounded by circular \emph{edges} that meet at \emph{vertices}. Notice that there are an even number of vertices on each circle. Given the circle, alternately colour the vertices on that circle red and blue. In doing so for each circle, every vertex is coloured twice — once for each of the two circles that cross at that point. If the two colourings agree at a vertex, then it is assigned that colour; otherwise, it becomes yellow. Show that, if some circle contains at least 2061 yellow points, then the vertices of some region are all yellow.",
        source="ISL",
        year=2018,
        topic="C",
        problem_number=7,
    ),




    Problem(
        problem_statement=r"Determine all pairs $(n, k)$ of distinct positive integers such that there exists a positive integer $s$ for which the numbers of divisors of $sn$ and of $sk$ are equal.",
        source="ISL",
        year=2018,
        topic="N",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $n>1$ be a positive integer. Each cell of an $n\times n$ table contains an integer. Suppose that the following conditions are satisfied: \begin{enumerate}[(i)]\item Each number in the table is congruent to $1$ modulo $n$; \item The sum of numbers in any row, as well as the sum of numbers in any column, is congruent to $n$ modulo $n^2$.\end{enumerate} Let $R_i$ be the product of the numbers in the $i$th row, and $C_j$ be the product of the numbers in the $j$th column. Prove that the sums $R_1+\cdots+R_n$ and $C_1+\cdots+C_n$ are congruent modulo $n^4$.",
        source="ISL",
        year=2018,
        topic="N",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Define the sequence $a_0$, $a_1$, $a_2$, $\dots$ by $a_n=2^n+2^{\lfloor n/2\rfloor}$. Prove that there are infinitely many terms of the sequence which can be expressed as a sum of (two or more) distinct terms of the sequence, as well as infinitely many of those which cannot be expressed in such a way.",
        source="ISL",
        year=2018,
        topic="N",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Let $a_1$, $a_2$, \dots , $a_n$, $\dots$  be a sequence of positive integers such that $$\frac{a_1}{a_2}+\frac{a_2}{a_3}+\cdots+\frac{a_{n-1}}{a_n}+\frac{a_n}{a_1}$$ is an integer for all $n\geqslant k$, where $k$ is some positive integer. Prove that there exists a positive integer $m$ such that $a_n=a_{n+1}$ for all $n\geqslant m$.",
        source="ISL",
        year=2018,
        topic="N",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Four positive integers $x$, $y$, $z$, and $t$ satisfy the relations $$xy-zt=x+y=z+t.$$ Is it possible that both $xy$ and $zt$ are perfect squares?",
        source="ISL",
        year=2018,
        topic="N",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Let $f : \{1, 2, 3, \dots\} \to \{2, 3, \dots\}$ be a function such that $f(m+n) \mid f(m)+f(n)$ for all pairs $m, n$ of positive integers. Prove that there exists a positive integer $c>1$ which divides all values of $f$.",
        source="ISL",
        year=2018,
        topic="N",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Let $n\geqslant2018$ be an integer, and let $a_1$, $a_2$, \dots , $a_n$, $b_1$, $b_2$, \dots , $b_n$ be pairwise distinct positive integers not exceeding $5n$. Suppose that the sequence $$\frac{a_1}{b_1}, \frac{a_2}{b_2}, \dots , \frac{a_n}{b_n}$$ forms an arithmetic progression. Prove that the terms of the sequence are equal.",
        source="ISL",
        year=2018,
        topic="N",
        problem_number=7,
    ),
])


ISL2017 = ProblemSet([
    Problem(
        problem_statement=r"Let $a_1$, $a_2$, \dots , $a_n$, $k$, and $M$ be positive integers such that $$\frac{1}{a_1}+\frac{1}{a_2}+\cdots+\frac{1}{a_n}=k\qquad\text{and}\qquad a_1a_2\dots a_n=M.$$ If $M>1$, prove that the polynomial $$P(x)=M(x+1)^k-(x+a_1)(x+a_2)\cdots(x+a_n)$$ has no positive roots.",
        source="ISL",
        year=2017,
        topic="A",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $q$ be a real number. Gugu has a napkin with ten distinct real numbers written on it, and he writes the following three lines of real numbers on the blackboard: \begin{itemize} \item In the first line, Gugu writes down every number of the form $a-b$, where $a$ and $b$ are two (not necessarily distinct) numbers on his napkin.\item In the second line, Gugu writes down every number of the form $qab$, where $a$ and $b$ are two (not necessarily distinct) numbers from the \emph{first line}.\item In the third line, Gugu writes down every number of the form $a^2+b^2-c^2-d^2$, where $a$, $b$, $c$, $d$ are four (not necessarily distinct) numbers from the \emph{first line}.\end{itemize} Determine all values of $q$ such that, regardless of the numbers on Gugu's napkin, every number in the second line is also a number in the third line.",
        source="ISL",
        year=2017,
        topic="A",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Let $S$ be a finite set, and let $\mathcal{A}$ be the set of all functions from $S$ to $S$. Let $f$ b  an element of $\mathcal{A}$, and let $T=f(S)$ be the image of $S$ under $f$. Suppose that $f\circ g\circ f\neq g\circ f\circ g$ for every $g$ in $\mathcal{A}$ with $g\neq f$. Show that $f(T)=T$.",
        source="ISL",
        year=2017,
        topic="A",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"A sequence of real numbers $a_1$, $a_2$, $\dots$ satisfies the relation $$a_n=-\max_{i+j=n}\left(a_i+a_j\right)\qquad\text{for all }n>2017.$$ Prove that this sequence is bounded, i.e., there is a constant $M$ such that $\left\lvert a_n\right\rvert\leqslant M$ for all positive integers $n$.",
        source="ISL",
        year=2017,
        topic="A",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"An integer $n\geqslant3$ is given. We call an $n$-tuple of real numbers $(x_1, x_2, \dots , x_n)$ \emph{Shiny} if for each permutation $y_1$, $y_2$, \dots , $y_n$ of these numbers we have $$\sum_{i=1}^{n-1}y_iy_{i+1}=y_1y_2+y_2y_3+\cdots+y_{n-1}y_n\geqslant -1.$$ Find the largest constant $K=K(n)$ such that $$\sum_{1\leqslant i<j\leqslant n}x_ix_j\geqslant K$$ holds for every Shiny $n$-tuple $(x_1, x_2, \dots , x_n)$.",
        source="ISL",
        year=2017,
        topic="A",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Find all functions $f:\mathbb{R}\to\mathbb{R}$ such that $$f(f(x)f(y))+f(x+y)=f(xy)$$ for all $x,y\in\mathbb{R}$.",
        source="ISL",
        year=2017,
        topic="A",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Let $a_0$, $a_1$, $a_2$, \dots  be a sequence of integers and $b_0$, $b_1$, $b_2$, \dots  be a sequence of \emph{positive} integers such that $a_0=0$, $a_1=1$, and $$a_{n+1}=\begin{cases}a_nb_n+a_{n-1}, & \text{if }b_{n-1}=1 \\ a_nb_n-a_{n-1}, & \text{if }b_{n-1}>1\end{cases}\qquad\text{for }n=1,2,\dots.$$ Prove that at least one of the two numbers $a_{2017}$ and $a_{2018}$ must be greater than or equal to $2017$.",
        source="ISL",
        year=2017,
        topic="A",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Assume a function $f:\mathbb{R}\to\mathbb{R}$ satisfies the following condition: \\\\ \textit{For every $x,y\in\mathbb{R}$ such that $\left(f(x)+y\right)\left(f(y)+x\right)>0$ we have $f(x)+y=f(y)+x$}.\\\\ Prove that $f(x)+y\leqslant f(y)+x$ whenever $x>y$.",
        source="ISL",
        year=2017,
        topic="A",
        problem_number=8,
    ),



    Problem(
        problem_statement=r"A rectangle $\mathcal{R}$ with odd integer side lengths is divided into small rectangles with integer side lengths. Prove that there is at least one among the small rectangles whose distances from the four sides of $\mathcal{R}$ are either all odd or all even.",
        source="ISL",
        year=2017,
        topic="C",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $n$ be a positive integer. Define a \emph{chameleon} to be any sequence of $3n$ letters, with exactly $n$ ocurrences of each of the letters $a$, $b$, and $c$. Define a \emph{swap} to be the transposition of two adjacent letters in a chameleon. Prove that for any chameleon $X$, there exists a chameleon $Y$ such that $X$ cannot be changed to $Y$ using fewer than $3n^2/2$ swaps.",
        source="ISL",
        year=2017,
        topic="C",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Sir Alex plays the following game on a row of 9 cells. Initially, all cells are empty. In each move, Sir Alex is allowed to perform exactly one of the following two operations: \begin{enumerate}[(1)]\item Choose any number of the form $2^j$, where $j$ is a non-negative integer, and put it into an empty cell.\item Choose two (not necessarily adjacent) cells with the same number in them; denote that number by $2^j$. Replace the number in one of the cells with $2^{j+1}$ and erase the number in the other cell.\end{enumerate} At the end of the game, one cell contains the number $2^n$, where $n$ is a given positive integer, while the other cells are empty. Determine the maximum number of moves that Sir Alex could have made, in terms of $n$.",
        source="ISL",
        year=2017,
        topic="C",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Let $N\geqslant2$ be an integer. $N(N+1)$ soccer players, no two of the same height, stand in a row in some order. Coach Ralph wants to remove $N(N-1)$ people from this row so that in the remaining row of $2N$ players, no one stands between the two tallest ones, no one stands between the third and the fourth tallest ones, \dots , and finally no one stands between the two shortest ones. Show that this is always possible.",
        source="ISL",
        year=2017,
        topic="C",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"A hunter and an invisible rabbit play a game in the Euclidean plane. The hunter's starting point $H_0$ coincides with the rabbit's starting point $R_0$. In the $n$th round of the game ($n\geqslant1$), the following happens. \begin{enumerate}[(1)]\item First the invisible rabbit moves secretly and unobserved from its current point $R_{n-1}$ to some new point $R_n$ with $R_{n-1}R_n=1$.\item The hunter has a tracking device (e.g. dog) that returns an approximate position $R_n'$ of the rabbit, so that $R_nR_n'$\leqslant 1$.\item The hunter then visibly moves from point $H_{n-1}$ to a new point $H_n$ with $H_{n-1}H_n=1$.\end{enumerate} Is there a strategy for the hunter that guarantees that after $10^9$ such rounds the distance between the hunter and the rabbit is below 100?",
        source="ISL",
        year=2017,
        topic="C",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Let $n>1$ be an integer. An $n\times n\times n$ cube is composed of $n^3$ unit cubes. Each unit cube is painted with one color. For each $n\times n\times 1$ box consisting of $n^2$ unit cubes (of any of the three possible orientations), we consider the set of the colors present in that box (each color is listed only once). This way, we get $3n$ sets of colors, split into three groups according to the orientation. It happens that for every set in any group, the same set appears in both of the other groups. Determine, in terms of $n$, the maximal possible number of colors that are present.",
        source="ISL",
        year=2017,
        topic="C",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"For any finite sets $X$ and $Y$ of positive integers, denote by $f_X(k)$ the $k$th smallest positive integer not in $X$, and let $$X*Y=X\cup\{f_X(y) : y\in Y\}.$$ Let $A$ be a set of $a>0$ positive integers, and let $B$ be a set of $b>0$ positive integers. Prove that if $A*B=B*A$, then $$\underbrace{A*(A*\cdots*(A*(A*A))\dots)}_{A\text{ appears }b\text{ times}}=\underbrace{B*(B*\cdots*(B*(B*B))\dots)}_{B\text{ appears }a\text{ times}}.$$",
        source="ISL",
        year=2017,
        topic="C",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Let $n$ be a given positive integer. In the Cartesian plane, each lattice point with nonnegative coordinates initially contains a butterfly, and there are no other butterflies. The \emph{neighborhood} of a lattice point $c$ consists of all lattice points within the axis-aligned $(2n+1)\times(2n+1)$ square entered at $c$, apart from $c$ itself. We all a butterfly \emph{lonely}, \emph{crowded}, or \emph{comfortable}, depending on whether the number of butterflies in its neighborhood $N$ is respectively less than, greater than, or equal to half of the number of lattice points in $N$. Every minute, all lonely butterflies fly away simultaneously. This process goes on for as long as there are any lonely butterflies. Assuming that the process eventually stops, determine the number of comfortable butterflies at the final state.",
        source="ISL",
        year=2017,
        topic="C",
        problem_number=8,
    ),




    Problem(
        problem_statement=r"The sequence $a_0$, $a_1$, $a_2$, $\dots$  of positive integers satisfies $$a_{n+1}=\begin{cases}\sqrt{a_n}, & \text{if }\sqrt{a_n}\text{ is an integer}\\ a_n+3, & \text{otherwise}\end{cases}\qquad\text{for every }n\geqslant0.$$ Determine all values of $a_0>1$ for which there is at least one number $a$ such that $a_n=a$ for infinitely many values of $n$.",
        source="ISL",
        year=2017,
        topic="N",
        problem_number=1,
    ),
    Problem(
        problem_statement=r"Let $p\geqslant2$ be a prime number. Eduardo and Fernando play the following game making moves alternately: in each move, the current player chooses an index $i$ in the set $\{0, 1, \dots , p-1\}$ that was not chosen before by either of the two players and then chooses an element $a_i$ of the set $\{0, 1, 2, 3, 4, 5, 6, 7, 8, 9\}$. Eduardo has the first move. The game ends after all the indices $i\in\{0, 1, \dots , p-1\}$ have been chosen. Then the following number is computed: $$M=a_0+10\cdot a_1+\cdots+10^{p-1}\cdot a_{p-1}=\sum_{j=0}^{p-1}a_j\cdot10^j.$$ The goal of Eduardo is to make the number $M$ divisible by $p$, and the goal of Fernando is to prevent this. Prove that Eduardo has a winning strategy.",
        source="ISL",
        year=2017,
        topic="N",
        problem_number=2,
    ),
    Problem(
        problem_statement=r"Determine all integers $n\geqslant2$ with the following property: for any integers $a_1$, $a_2$, \dots , $a_n$ whose sum is not divisible by $n$, there exists an index $1\leqslant i\leqslant n$ such that none of the numbers $$a_i, a_i+a_{i+1}, \dots , a_i+a_{i+1}+\cdots+a_{i+n-1}$$ is divisible by $n$. (We let $a_i=a_{i-n}$ when $i>n$.)",
        source="ISL",
        year=2017,
        topic="N",
        problem_number=3,
    ),
    Problem(
        problem_statement=r"Call a rational number \emph{short} if it has finitely many digits in its decimal expansion. For a positive integer $m$, we say that a positive integer $t$ is $m$-\emph{tastic} if there exists a number $c\in\{1, 2, 3, \dots , 2017\}$ such that $\frac{10^t-1}{c\cdot m}$ is short, and such that $\frac{10^k-1}{c\cdot m}$ is not short for any $1\leqslant k<t$. Let $S(m)$ be the set of $m$-tastic numbers. Consider $S(m)$ for $m=1, 2, \dots$. What is the maximum number of elements in $S(m)$?",
        source="ISL",
        year=2017,
        topic="N",
        problem_number=4,
    ),
    Problem(
        problem_statement=r"Find all pairs $(p, q)$ of prime numbers with $p>q$ for which the number $$\frac{(p+q)^{p+q}(p-q)^{p-q}-1}{(p+q)^{p-q}(p-q)^{p+q}-1}$$ is an integer.",
        source="ISL",
        year=2017,
        topic="N",
        problem_number=5,
    ),
    Problem(
        problem_statement=r"Find the smallest positive integer $n$, or show that no such $n$ exists, with the following property: there are infinitely many distinct $n$-tuples of positive rational numbers $(a_1, a_2, \dots , a_n)$ such that both $$a_1+a_2+\cdots+a_n\qquad\text{and}\qquad\frac{1}{a_1}+\frac{1}{a_2}+\cdots+\frac{1}{a_n}$$ are integers.",
        source="ISL",
        year=2017,
        topic="N",
        problem_number=6,
    ),
    Problem(
        problem_statement=r"Say that an ordered pair $(x, y)$ of integers is an \emph{irreducible lattice point} if $x$ and $y$ are relatively prime. For any finite set $S$ of irreducible lattice points, show that there is a homogenous polynomial in two variables, $f(x, y)$, with integer coefficients, of degree at least 1, such that $f(x, y)=1$ for each $(x, y)$ in the set $S$.",
        source="ISL",
        year=2017,
        topic="N",
        problem_number=7,
    ),
    Problem(
        problem_statement=r"Let $p$ be an odd prime number. Suppose that a function $f : \mathbb{N}\times\mathbb{N} \to \{0, 1\}$ satisfies the following properties: \begin{itemize}\item $f(1,1)=0$;\item $f(a,b)+f(b,a)=1$ for any pair of relatively prime positive integers $(a,b)$ not both equal to $1$;\item $f(a+b,b)=f(a,b)$ for any pair of relatively prime positive integers $(a,b)$.\end{itemize} Prove that $$\sum_{n=1}^{p-1}f(n^2,p)\geqslant\sqrt{2p}-2.$$",
        source="ISL",
        year=2017,
        topic="N",
        problem_number=8,
    ),

])





ISL = ISL2017 + ISL2018 + ISL2019 + ISL2020 + ISL2021 + ISL2022